// <auto-generated />
using System;
using IdentityTenantManagementDatabase.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityTenantManagementDatabase.Migrations
{
    [DbContext(typeof(IdentityTenantManagementContext))]
    partial class IdentityTenantManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("TenantId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.DeletionPolicyConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PermanentDeletionEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("RetentionPeriodDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DeletionPolicyConfigurations");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("ExternalIdentities");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.ExternalIdentityEntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExternalIdentityEntityTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("86e6890c-0b3f-4278-bd92-a4fd2ea55413"),
                            EntityType = "user"
                        },
                        new
                        {
                            Id = new Guid("f6d6e7fc-8998-4b77-ad31-552e5c76c3dd"),
                            EntityType = "tenant"
                        });
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.GlobalSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("GlobalSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ceb4c8ae-4af4-4a94-ac54-56da00fc7b1e"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "When enabled, users must have a role or permission themselves before they can grant it to others",
                            Key = "RequirePermissionToGrant",
                            Value = "true"
                        });
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.IdentityProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityProviders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("049284c1-ff29-4f28-869f-f64300b69719"),
                            BaseUrl = "http://localhost:8080/",
                            CreatedAt = new DateTime(2025, 10, 14, 1, 37, 0, 0, DateTimeKind.Utc),
                            Name = "Keycloak",
                            ProviderType = "oidc"
                        });
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f678-90ab-cdef-1234-56789abcdef0"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Invite new users to the organization",
                            DisplayName = "Invite Users",
                            Name = "invite-users",
                            PermissionGroupId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("e5f67890-abcd-ef12-3456-789abcdef012"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View organization users",
                            DisplayName = "View Users",
                            Name = "view-users",
                            PermissionGroupId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("f6789abc-def1-2345-6789-abcdef012345"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update user information",
                            DisplayName = "Update Users",
                            Name = "update-users",
                            PermissionGroupId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("0789abcd-ef12-3456-789a-bcdef0123456"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Remove users from the organization",
                            DisplayName = "Delete Users",
                            Name = "delete-users",
                            PermissionGroupId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("189abcde-f123-4567-89ab-cdef01234567"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assign roles and permissions to users",
                            DisplayName = "Assign Permissions",
                            Name = "assign-permissions",
                            PermissionGroupId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("29abcdef-0123-4567-89ab-cdef12345678"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modify organization settings and configuration",
                            DisplayName = "Update Organization Settings",
                            Name = "update-org-settings",
                            PermissionGroupId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PermissionGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permissions related to system administration and user management",
                            DisplayName = "System Administration",
                            Name = "SystemAdministration"
                        });
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.RegistrationFailureLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FailedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeycloakTenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KeycloakUserRolledBack")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegistrationFailureLogs");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full access to organization settings and user management",
                            DisplayName = "Organization Administrator",
                            Name = "org-admin"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f678-90ab-cdef-123456789abc"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Can invite and manage organization users",
                            DisplayName = "Organization Manager",
                            Name = "org-manager"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-7890-abcd-ef12-3456789abcde"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standard organization member with no special permissions",
                            DisplayName = "Organization User",
                            Name = "org-user"
                        });
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0d5987e-b3ab-4927-912c-5c43eab14199"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("d4e5f678-90ab-cdef-1234-56789abcdef0"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("fc30f474-088f-4a84-8116-101669a019e8"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("e5f67890-abcd-ef12-3456-789abcdef012"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("4675a21c-87af-4db2-aedd-c8be3c193cbb"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("f6789abc-def1-2345-6789-abcdef012345"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("3a8966f3-2f08-4eaa-84de-38b7e8cc4ce6"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("0789abcd-ef12-3456-789a-bcdef0123456"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("c070512f-94b2-4870-95e2-cc0185e9d4da"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("189abcde-f123-4567-89ab-cdef01234567"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("fff5cbc7-0965-4bd1-9be8-74314917625f"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("29abcdef-0123-4567-89ab-cdef12345678"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("ac52b94d-98c5-4aca-a5ce-1769b4b1e8b3"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("d4e5f678-90ab-cdef-1234-56789abcdef0"),
                            RoleId = new Guid("b2c3d4e5-f678-90ab-cdef-123456789abc")
                        },
                        new
                        {
                            Id = new Guid("b7ba3ab6-1406-41de-93fc-f085b164beb8"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("e5f67890-abcd-ef12-3456-789abcdef012"),
                            RoleId = new Guid("b2c3d4e5-f678-90ab-cdef-123456789abc")
                        },
                        new
                        {
                            Id = new Guid("59ce4598-6a76-443c-a5af-21d95c22e98a"),
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("f6789abc-def1-2345-6789-abcdef012345"),
                            RoleId = new Guid("b2c3d4e5-f678-90ab-cdef-123456789abc")
                        });
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.TenantDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("TenantDomain");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("TenantUsers");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.TenantUserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InactiveAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InactiveAt")
                        .HasFilter("[InactiveAt] IS NOT NULL");

                    b.HasIndex("TenantUserId")
                        .IsUnique();

                    b.HasIndex("UserProfileId");

                    b.ToTable("TenantUserProfiles");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.TenantUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantUserId", "RoleId")
                        .IsUnique();

                    b.ToTable("TenantUserRoles");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionFailedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionFailedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DeletionRetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GloballyInactiveAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeletionFailedAt")
                        .HasFilter("[DeletionFailedAt] IS NOT NULL");

                    b.HasIndex("GloballyInactiveAt")
                        .HasFilter("[GloballyInactiveAt] IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("TenantUserId", "PermissionId")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.UserStatusType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserStatusTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90a89389-7891-4784-90df-f556e95bccd9"),
                            CreatedAt = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "User account is active and can access the system",
                            DisplayName = "Active",
                            Name = "active"
                        },
                        new
                        {
                            Id = new Guid("7f313e08-f83e-43df-b550-c11014592ab7"),
                            CreatedAt = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "User account is inactive and cannot access the system",
                            DisplayName = "Inactive",
                            Name = "inactive"
                        },
                        new
                        {
                            Id = new Guid("52ee270f-d6de-4f96-a578-3c8e84af4b9b"),
                            CreatedAt = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "User account has been temporarily suspended",
                            DisplayName = "Suspended",
                            Name = "suspended"
                        },
                        new
                        {
                            Id = new Guid("3981b8f5-ffbd-426a-abde-a723631b3536"),
                            CreatedAt = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "User account is pending activation or verification",
                            DisplayName = "Pending",
                            Name = "pending"
                        });
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.AuditLog", b =>
                {
                    b.HasOne("IdentityTenantManagementDatabase.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityTenantManagementDatabase.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.ExternalIdentity", b =>
                {
                    b.HasOne("IdentityTenantManagementDatabase.Models.ExternalIdentityEntityType", "EntityType")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdentityTenantManagementDatabase.Models.IdentityProvider", "Provider")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdentityTenantManagementDatabase.Models.Tenant", null)
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("TenantId");

                    b.HasOne("IdentityTenantManagementDatabase.Models.User", null)
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("UserId");

                    b.Navigation("EntityType");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.Permission", b =>
                {
                    b.HasOne("IdentityTenantManagementDatabase.Models.PermissionGroup", "PermissionGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.RolePermission", b =>
                {
                    b.HasOne("IdentityTenantManagementDatabase.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityTenantManagementDatabase.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.TenantDomain", b =>
                {
                    b.HasOne("IdentityTenantManagementDatabase.Models.Tenant", "Tenant")
                        .WithMany("Domains")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.TenantUser", b =>
                {
                    b.HasOne("IdentityTenantManagementDatabase.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IdentityTenantManagementDatabase.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IdentityTenantManagementDatabase.Models.User", null)
                        .WithMany("TenantUsers")
                        .HasForeignKey("UserId1");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.TenantUserProfile", b =>
                {
                    b.HasOne("IdentityTenantManagementDatabase.Models.TenantUser", "TenantUser")
                        .WithMany()
                        .HasForeignKey("TenantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityTenantManagementDatabase.Models.UserProfile", "UserProfile")
                        .WithMany("TenantUserProfiles")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TenantUser");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.TenantUserRole", b =>
                {
                    b.HasOne("IdentityTenantManagementDatabase.Models.Role", "Role")
                        .WithMany("TenantUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdentityTenantManagementDatabase.Models.TenantUser", "TenantUser")
                        .WithMany("TenantUserRoles")
                        .HasForeignKey("TenantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("TenantUser");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.User", b =>
                {
                    b.HasOne("IdentityTenantManagementDatabase.Models.Tenant", null)
                        .WithMany("Users")
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.UserPermission", b =>
                {
                    b.HasOne("IdentityTenantManagementDatabase.Models.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IdentityTenantManagementDatabase.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityTenantManagementDatabase.Models.TenantUser", "TenantUser")
                        .WithMany()
                        .HasForeignKey("TenantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrantedByUser");

                    b.Navigation("Permission");

                    b.Navigation("TenantUser");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.UserProfile", b =>
                {
                    b.HasOne("IdentityTenantManagementDatabase.Models.UserStatusType", "Status")
                        .WithMany("UserProfiles")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.ExternalIdentityEntityType", b =>
                {
                    b.Navigation("ExternalIdentities");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.IdentityProvider", b =>
                {
                    b.Navigation("ExternalIdentities");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("TenantUserRoles");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.Tenant", b =>
                {
                    b.Navigation("Domains");

                    b.Navigation("ExternalIdentities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.TenantUser", b =>
                {
                    b.Navigation("TenantUserRoles");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.User", b =>
                {
                    b.Navigation("ExternalIdentities");

                    b.Navigation("TenantUsers");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.UserProfile", b =>
                {
                    b.Navigation("TenantUserProfiles");
                });

            modelBuilder.Entity("IdentityTenantManagementDatabase.Models.UserStatusType", b =>
                {
                    b.Navigation("UserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
